package packer

import (
	"sort"

	"github.com/kenfaulkner/trucktetris/internal/domain"
)

// Stacker is the M5 packer. It extends the volume-only sweep with real
// stacking: cases may rest on the floor or fully on top of a single supporting
// case, subject to stacking-type rules, per-case bearing capacity, and the
// truck's gross weight limit.
//
// Simplifying rules for this milestone:
//   - A stacked case must rest entirely on top of exactly one supporting case
//     (its base footprint fits within that case's top face). No bridging across
//     multiple boxes.
//   - Candidate positions are extreme points: the origin, plus the far corners
//     generated by each placed case.
type Stacker struct{}

// placed is an internal record tracking the support chain and borne weight.
type placed struct {
	c      domain.Case
	min    [3]int // origin corner
	max    [3]int // opposite corner
	up     domain.Axis
	parent int // index into placements of the supporting case, or -1 for floor
}

type point struct{ x, y, z int }

// Pack implements Packer.
func (Stacker) Pack(req domain.SolveRequest) domain.LoadPlan {
	t := req.Truck

	// Heaviest first: keeps heavy cases low, helps the axle work in M6, and
	// gives light cases something solid to sit on.
	cases := make([]domain.Case, len(req.Cases))
	copy(cases, req.Cases)
	sort.SliceStable(cases, func(i, j int) bool {
		if cases[i].Weight != cases[j].Weight {
			return cases[i].Weight > cases[j].Weight
		}
		return volume(cases[i]) > volume(cases[j])
	})

	plan := domain.LoadPlan{Truck: t, Placements: []domain.Placement{}, Unplaced: []string{}}
	var boxes []placed
	borne := map[int]int{} // placement index -> weight currently resting above it
	total := 0

	points := []point{{0, 0, 0}}
	var loads []domain.PointLoad // point loads of placed cases, for axle checks

	for _, c := range cases {
		if total+c.Weight > t.GrossMax {
			plan.Unplaced = append(plan.Unplaced, c.ID)
			continue
		}

		pos, o, parent, ok := findSpot(c, t, boxes, borne, points, loads)
		if !ok {
			plan.Unplaced = append(plan.Unplaced, c.ID)
			continue
		}

		p := placed{
			c:      c,
			min:    [3]int{pos.x, pos.y, pos.z},
			max:    [3]int{pos.x + o.dx, pos.y + o.dy, pos.z + o.dz},
			up:     o.up,
			parent: parent,
		}
		boxes = append(boxes, p)

		// Add this case's weight to every ancestor in the support chain.
		for a := parent; a != -1; a = boxes[a].parent {
			borne[a] += c.Weight
		}
		total += c.Weight
		loads = append(loads, caseLoad(p.min[0], o.dx, c.Weight))

		plan.Placements = append(plan.Placements, domain.Placement{
			CaseID: c.ID,
			Pos:    [3]int{p.min[0], p.min[1], p.min[2]},
			Size:   [3]int{o.dx, o.dy, o.dz},
			Up:     o.up,
		})
		plan.Summary.TotalWeight += c.Weight

		// New extreme points at the far corners of the placed box.
		points = append(points,
			point{p.max[0], p.min[1], p.min[2]},
			point{p.min[0], p.max[1], p.min[2]},
			point{p.min[0], p.min[1], p.max[2]},
		)
	}

	plan.Summary.PlacedCount = len(plan.Placements)
	plan.Summary.UnplacedCount = len(plan.Unplaced)
	plan.Summary.VolumeUtilPct = volumeUtilPct(t, plan.Placements)
	plan.Summary.WeightUtilPct = pct(plan.Summary.TotalWeight, t.GrossMax)
	plan.AxleLoads = domain.ComputeAxleLoads(t, loads)
	return plan
}

// volumeUtilPct is placed volume as a percentage of the truck's load space.
func volumeUtilPct(t domain.Truck, placements []domain.Placement) int {
	truckVol := t.Dim.L * t.Dim.W * t.Dim.H
	used := 0
	for _, p := range placements {
		used += p.Size[0] * p.Size[1] * p.Size[2]
	}
	return pct(used, truckVol)
}

// pct returns 100*num/den as a rounded integer, or 0 when den <= 0.
func pct(num, den int) int {
	if den <= 0 {
		return 0
	}
	return int(float64(num)/float64(den)*100 + 0.5)
}

// caseLoad builds the point load for a placed case: its weight acting at the
// centre of its footprint along the truck length.
func caseLoad(minX, dx, weight int) domain.PointLoad {
	return domain.PointLoad{X: minX + dx/2, Weight: weight}
}

// findSpot searches candidate points and orientations for a legal placement of
// c. Points are tried lowest-first so cases settle down rather than float high;
// as a tie-break they are biased toward the nearest axle so heavy cases sit
// over the axles. A candidate is rejected if adding c there would overload any
// axle.
func findSpot(c domain.Case, t domain.Truck, boxes []placed, borne map[int]int, points []point, loads []domain.PointLoad) (point, orientation, int, bool) {
	// Only heavy cases are biased over the axles; lighter cases pack for
	// density (lowest, then front-most).
	biasToAxle := t.IsHeavy(c.Weight)

	cand := make([]point, len(points))
	copy(cand, points)
	sort.SliceStable(cand, func(i, j int) bool {
		if cand[i].z != cand[j].z {
			return cand[i].z < cand[j].z
		}
		if biasToAxle {
			if di, dj := axleDist(t, cand[i].x), axleDist(t, cand[j].x); di != dj {
				return di < dj
			}
		}
		if cand[i].x != cand[j].x {
			return cand[i].x < cand[j].x
		}
		return cand[i].y < cand[j].y
	})

	for _, pt := range cand {
		for _, o := range orientations(c) {
			bmin := [3]int{pt.x, pt.y, pt.z}
			bmax := [3]int{pt.x + o.dx, pt.y + o.dy, pt.z + o.dz}

			if bmax[0] > t.Dim.L || bmax[1] > t.Dim.W || bmax[2] > t.Dim.H {
				continue
			}
			if overlapsAny(bmin, bmax, boxes) {
				continue
			}
			parent, ok := support(c, bmin, bmax, boxes, borne)
			if !ok {
				continue
			}
			if !axleFeasible(t, loads, caseLoad(pt.x, o.dx, c.Weight)) {
				continue
			}
			return pt, o, parent, true
		}
	}
	return point{}, orientation{}, -1, false
}

// axleDist returns the distance from x to the nearest axle, or 0 when the truck
// has no axles (so the bias becomes a no-op).
func axleDist(t domain.Truck, x int) int {
	if len(t.Axles) == 0 {
		return 0
	}
	best := -1
	for _, a := range t.Axles {
		d := x - a.Position
		if d < 0 {
			d = -d
		}
		if best == -1 || d < best {
			best = d
		}
	}
	return best
}

// axleFeasible reports whether adding one more point load keeps every axle
// within its limit. Trucks with no axles are always feasible.
func axleFeasible(t domain.Truck, loads []domain.PointLoad, add domain.PointLoad) bool {
	if len(t.Axles) == 0 {
		return true
	}
	trial := make([]domain.PointLoad, len(loads)+1)
	copy(trial, loads)
	trial[len(loads)] = add
	for _, al := range domain.ComputeAxleLoads(t, trial) {
		if al.Over {
			return false
		}
	}
	return true
}

// support checks that a box occupying [bmin,bmax] is properly supported and,
// if stacked, that the stacking rules and weight limits hold. It returns the
// index of the supporting case (-1 for the floor).
func support(c domain.Case, bmin, bmax [3]int, boxes []placed, borne map[int]int) (int, bool) {
	if bmin[2] == 0 {
		return -1, true // resting on the truck floor
	}

	// Find a single placed box whose top face is at bmin[2] and fully covers
	// this box's base footprint.
	for i, b := range boxes {
		if b.max[2] != bmin[2] {
			continue
		}
		covers := b.min[0] <= bmin[0] && b.max[0] >= bmax[0] &&
			b.min[1] <= bmin[1] && b.max[1] >= bmax[1]
		if !covers {
			continue
		}
		// The supporting case must permit stacking at all, and the type-level
		// rule on this case must accept the supporting case's type.
		if !b.c.Stackable || !stackableOn(c, b.c.Type) {
			continue
		}
		// Weight: this case plus everything already on b must not exceed b's
		// bearing capacity, and the same must hold for every ancestor below b.
		if !canBear(c.Weight, i, boxes, borne) {
			continue
		}
		return i, true
	}
	return -1, false
}

// canBear reports whether adding weight w on top of box index i is within the
// bearing capacity of box i and every box below it in the support chain.
func canBear(w, i int, boxes []placed, borne map[int]int) bool {
	for a := i; a != -1; a = boxes[a].parent {
		if borne[a]+w > boxes[a].c.MaxStackWeight {
			return false
		}
	}
	return true
}

func stackableOn(c domain.Case, supportType string) bool {
	for _, ty := range c.StackableOn {
		if ty == supportType {
			return true
		}
	}
	return false
}

func overlapsAny(bmin, bmax [3]int, boxes []placed) bool {
	for _, b := range boxes {
		if overlap3D(bmin, bmax, b.min, b.max) {
			return true
		}
	}
	return false
}

// overlap3D reports whether two axis-aligned boxes share interior volume.
// Touching faces do not count as overlap.
func overlap3D(amin, amax, bmin, bmax [3]int) bool {
	for i := range 3 {
		if amax[i] <= bmin[i] || bmax[i] <= amin[i] {
			return false
		}
	}
	return true
}
